Lc5 기능 설명 작성
bsgp/docs pull request #2
Opened 2024-07-15 07:17 UTC by sadie100

2024-07-15 07:44 UTC, gnseo requested changes
그리고 내용을 조금 더 자세하게, 풍부하게 작성하면 좋겠습니다.

2024-07-15 07:44 UTC, gnseo commented on mkdocs.yml
> +
아래와 같은 구조로 문서를 만들어주세요.

```suggestion
      - "미리 정의된 컴포넌트 라이브러리": 'lc5/prebuilt_components.md'
      - "미리보기": 'lc5/preview.md'
      - "반응형 디자인 지원": "lc5/responsive.md"
      - "데이터 바인딩": "lc5/binding.md"
      - "템플릿 및 테마": "lc5/templates.md"
      - "버전 관리": "lc5/versioning.md"
```

2024-07-19 05:03 UTC, gnseo commented
현상태를 draft로 변경했습니다. 완료되면 "Ready for review"를 클릭하면 될겁니다.
<img width="898" alt="Screenshot 2024-07-19 at 14 03 12" src="https://github.com/user-attachments/assets/b37721f7-e176-4249-acb1-9eaa961f6f37">

2024-07-24 05:10 UTC, sadie100 commented
팀장님 라이브러리 공식문서 스타일로 일단 써보긴 했는데 다 쓰고 나니 log랑 굉장히 비슷한 내용구성이 된것 같아 이게 의도하신 게 맞는가 싶은데요, 한번 리뷰해주시면 감사하겠습니다.

2024-07-24 05:20 UTC, gnseo approved these changes

2024-07-24 05:21 UTC, gnseo commented
> 팀장님 라이브러리 공식문서 스타일로 일단 써보긴 했는데 다 쓰고 나니 log랑 굉장히 비슷한 내용구성이 된것 같아 이게 의도하신 게 맞는가 싶은데요, 한번 리뷰해주시면 감사하겠습니다.

PR에서는 비주얼을 확인할수 없어서 일단 배포하고 보겠습니다.

2024-07-24 05:21 UTC, merged